-- Campos alineados con la tabla Pacientes de Access (Control Salud.exe / Datos.mdb).
-- Ejecutar UNA vez sobre la base que ya tiene `pacientes` (después de schema_mysql.sql).
-- Tipos: Access BIT → TINYINT(1), LONGCHAR → LONGTEXT.

SET NAMES utf8mb4;

ALTER TABLE pacientes
  ADD COLUMN numehistoria VARCHAR(30) NULL COMMENT 'Access: numehistoria',
  ADD COLUMN embarazo TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Access: Embarazo',
  ADD COLUMN ulti_emba SMALLINT NULL COMMENT 'Access: UltiEmba',
  ADD COLUMN ultima_cons DATETIME NULL COMMENT 'Access: UltimaCons',
  ADD COLUMN paciente_inactivo TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Access: pacienteinactivo',
  ADD COLUMN motivo_inactividad VARCHAR(250) NULL COMMENT 'Access: motivoinactividad',
  ADD COLUMN cobertura SMALLINT NULL COMMENT 'Access: cobertura',
  ADD COLUMN id_cobertura INT NULL COMMENT 'Access: idcobertura',
  ADD COLUMN nro_os VARCHAR(30) NULL COMMENT 'Access: NroOS',
  ADD COLUMN apellido VARCHAR(30) NULL COMMENT 'Access: Apellido',
  ADD COLUMN apellido2 VARCHAR(30) NULL COMMENT 'Access: apellido2',
  ADD COLUMN fe_nac DATETIME NULL COMMENT 'Access: FeNac',
  ADD COLUMN sexo SMALLINT NULL COMMENT 'Access: sexo',
  ADD COLUMN dni_sin_uso VARCHAR(10) NULL COMMENT 'Access: DNISinUso',
  ADD COLUMN id_tipo_doc INT NULL COMMENT 'Access: idtipodoc',
  ADD COLUMN id_ocupacion INT NULL COMMENT 'Access: idocupacion',
  ADD COLUMN detalle_ocupacion VARCHAR(250) NULL COMMENT 'Access: detallesocupacion',
  ADD COLUMN tel_celular VARCHAR(30) NULL COMMENT 'Access: TelCelular',
  ADD COLUMN tel_laboral VARCHAR(30) NULL COMMENT 'Access: TelLaboral',
  ADD COLUMN nombre_padre VARCHAR(30) NULL COMMENT 'Access: nombrepadre',
  ADD COLUMN naci_padre DATETIME NULL COMMENT 'Access: nacipadre',
  ADD COLUMN id_ocupacion_padre INT NULL COMMENT 'Access: idocupacionpadre',
  ADD COLUMN horas_hogar_padre VARCHAR(10) NULL COMMENT 'Access: horashogarpadre',
  ADD COLUMN nombre_madre VARCHAR(30) NULL COMMENT 'Access: nombremadre',
  ADD COLUMN naci_madre DATETIME NULL COMMENT 'Access: nacimadre',
  ADD COLUMN id_ocupacion_madre INT NULL COMMENT 'Access: idocupacionmadre',
  ADD COLUMN horas_hogar_madre VARCHAR(10) NULL COMMENT 'Access: horashogarmadre',
  ADD COLUMN nro_hermanos VARCHAR(2) NULL COMMENT 'Access: nrohermanos',
  ADD COLUMN edad_hermanos VARCHAR(50) NULL COMMENT 'Access: edadhermanos',
  ADD COLUMN nro_hermanas VARCHAR(2) NULL COMMENT 'Access: nrohermanas',
  ADD COLUMN edad_hermanas VARCHAR(50) NULL COMMENT 'Access: edadhermanas',
  ADD COLUMN detalles_familia VARCHAR(250) NULL COMMENT 'Access: detallesfamilia',
  ADD COLUMN ape1_contacto VARCHAR(30) NULL COMMENT 'Access: ape1contacto',
  ADD COLUMN ape2_contacto VARCHAR(30) NULL COMMENT 'Access: ape2contacto',
  ADD COLUMN nombre_contacto VARCHAR(30) NULL COMMENT 'Access: nombrecontacto',
  ADD COLUMN id_relacion INT NULL COMMENT 'Access: idrelacion',
  ADD COLUMN tel_par_contacto VARCHAR(30) NULL COMMENT 'Access: telparcontacto',
  ADD COLUMN tel_cel_contacto VARCHAR(30) NULL COMMENT 'Access: telcelcontacto',
  ADD COLUMN tel_lab_contacto VARCHAR(30) NULL COMMENT 'Access: tellabcontacto',
  ADD COLUMN id_estado_civil INT NULL COMMENT 'Access: idestadocivil',
  ADD COLUMN id_etnia INT NULL COMMENT 'Access: idetnia',
  ADD COLUMN id_ciudad INT NULL COMMENT 'Access: idciudad',
  ADD COLUMN cp VARCHAR(10) NULL COMMENT 'Access: CP',
  ADD COLUMN id_provincia INT NULL COMMENT 'Access: idprovincia',
  ADD COLUMN id_pais INT NULL COMMENT 'Access: idpais',
  ADD COLUMN id_estatus INT NULL COMMENT 'Access: idestatus',
  ADD COLUMN alergias LONGTEXT NULL COMMENT 'Access: alergias',
  ADD COLUMN grupo_sanguineo SMALLINT NULL COMMENT 'Access: GrupoSanguineo',
  ADD COLUMN factor_sanguineo SMALLINT NULL COMMENT 'Access: FactorSanguineo',
  ADD COLUMN hc_texto LONGTEXT NULL COMMENT 'Access: HC',
  ADD COLUMN referente VARCHAR(100) NULL COMMENT 'Access: referente',
  ADD COLUMN id_cobertura2 INT NULL COMMENT 'Access: idcobertura2',
  ADD COLUMN nu_afiliado2 VARCHAR(30) NULL COMMENT 'Access: nuafiliado2',
  ADD COLUMN antecedentes_hc LONGTEXT NULL COMMENT 'Access: antecedenteshc',
  ADD COLUMN id_plan INT NULL COMMENT 'Access: idplan',
  ADD COLUMN paga_iva SMALLINT NULL COMMENT 'Access: pagaiva',
  ADD COLUMN alta_paci_web SMALLINT NULL COMMENT 'Access: altapaciweb',
  ADD COLUMN identidad_gen SMALLINT NULL COMMENT 'Access: identidadgen',
  ADD COLUMN orientacion_sex SMALLINT NULL COMMENT 'Access: orientacionsex';

-- Mapeo sugerido import Access → columnas web ya existentes:
--   Tel → telefono | Domicilio → direccion | Email → email | FeNac → fecha_nacimiento (DATE) o fe_nac
-- pacienteinactivo vs activo: invertir (activo = NOT pacienteinactivo) o usar solo una convención en la app.
